cls_tool/cls_tool/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', auth_views.LoginView.as_view(), name='login'),
    path(r'classifier/', include(('news.urls', 'news'), namespace='newsurls')),
]

urlpatterns += staticfiles_urlpatterns()

cls_tool/news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(r'done/', views.edit, name='list_done'),
    path(r'edit/<int:pk>/', views.edit_done, name='edit_done'),
    path(r'ajax/feedback/', views.feedback, name='feedback'),
    path(r'', views.classify, name='classify'),
]

cls_tool/news/models.py
from django.db import models
from django.contrib.auth.models import User

class FakeType(models.Model):
    label = models.CharField(max_length=255)
    description = models.TextField(null=True)
    id = models.IntegerField(primary_key=True)

    def __str__(self):
        return self.label

    class Meta:
        ordering = ('id', )

class Article(models.Model):
    html_id = models.IntegerField(primary_key=True)
    real_url = models.TextField(null=True)
    ra_summary = models.TextField(null=True)
    ra_title = models.TextField(null=True)
    loaded_unix = models.PositiveIntegerField()
    bee = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return '#{id}: {title}'.format(id=self.html_id, title=self.ra_title)

class Classified(models.Model):
    types = models.ManyToManyField(FakeType)
    article = models.ForeignKey(Article, on_delete=models.PROTECT)
    classified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'#{self.article.html_id} by {self.article.bee}: {self.article.ra_title}'
    class Meta:
        verbose_name_plural = 'Classified'


class Feedback(models.Model):
    article = models.ForeignKey(Article, on_delete=models.PROTECT)
    written_at = models.DateTimeField(auto_now=True)
    comment = models.TextField()

    def __str__(self):
        return f'{self.article.bee} for "{self.article.ra_title}" at {self.written_at}'

cls_tool/news/forms.py
from django import forms
from . import models

class NewClassify(forms.ModelForm):
    class Meta:
        model = models.Classified
        fields = ['types', 'article']

    def __init__(self, *args, **kwargs):
        super(NewClassify, self).__init__(*args, **kwargs)
        self.fields['types'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['types'].queryset = models.FakeType.objects.all()
        self.fields['article'].widget = forms.widgets.HiddenInput()
        self.fields['article'].required = True


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.Feedback
        fields = ['article', 'comment']

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.fields['article'].widget = forms.widgets.HiddenInput()
        self.fields['article'].required = True

cls_tool/news/views.py
from django.shortcuts import render
from . import models, forms
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.forms.models import model_to_dict


@login_required
def classify(request):
    if request.method == 'POST':
        form = forms.NewClassify(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/classifier/')

    else:
        explanations = ';;'.join([t.description for t in models.FakeType.objects.all()])
        classified_new = models.Article.objects.filter(bee=request.user
                                                       ).exclude(html_id__in=models.Classified.objects.all(
                                                       ).values('article')
                                                       ).order_by('?'
                                                       ).first()
        form = forms.NewClassify(initial={'article': classified_new})
        feedback = forms.FeedbackForm(initial={'article': classified_new})
        done_counter = models.Classified.objects.filter(article__bee=request.user).count()

        return render(request, 'classifier.html', {'cls_new': classified_new,
                                                   'form': form,
                                                   'type_explanations': explanations,
                                                   'feedback': feedback,
                                                   'done_counter': done_counter,
                                                   })


@login_required
def edit(request):
    selected_type = request.GET.get('type')

    print(request.GET.get('types'))
    types = models.FakeType.objects.all()
    if not selected_type or selected_type == 'all':
        classified_before = models.Classified.objects.filter(article__bee=request.user
                                                             ).order_by('-classified_at')
    else:
        classified_before = models.Classified.objects.filter(article__bee=request.user
                                                             ).filter(types__label=selected_type
                                                             ).order_by('-classified_at')
    paginator = Paginator(classified_before, 15)

    page = request.GET.get('page')
    try:
        done = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        done = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        done = paginator.page(paginator.num_pages)

    return render(request, 'list_done.html', {'done': done,
                                              'types': types,
                                              'selected_type': selected_type})


@login_required
def edit_done(request, pk):
    article = models.Classified.objects.get(article__html_id=pk)
    if request.method == 'POST':
        form = forms.NewClassify(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/classifier/done/')
    else:
        explanations = ';;'.join([t.description for t in models.FakeType.objects.all()])

        feedback = forms.FeedbackForm(initial={'article': article.article})
        form = forms.NewClassify(instance=article, data=model_to_dict(article))

        return render(request, 'edit_done.html', {'form': form,
                                                  'cls_article': article,
                                                  'type_explanations': explanations,
                                                  'feedback': feedback,
                                                  })


@login_required
def feedback(request):
    if request.method == 'POST':
        feedback = forms.FeedbackForm(request.POST)
        if feedback.is_valid():
            feedback.save()
            return JsonResponse({'ok': True})

cls_tool/templates/classifier.html
{% extends "sceleton.html" %}

{% load static from staticfiles %}

{% block content %}
<div class="container-fluid">
    <div class="row align-items-middle mt-2 mb-3">
        <div class="col-1 text-center">
            {% url 'newsurls:list_done' as done_url %}
            <a href="{{ done_url }}">
                <i class="fa fa-clock-o fa-2x" aria-hidden="true"></i>
            </a>
        </div>
        <div class="col-10" id="heading">
            <h1><a href="{{ cls_new.real_url }}" target="_blank" class="link">#{{ cls_new.html_id }}</a>: {{ cls_new.ra_title }}</h1>
        </div>
        <div class="col-1 text-center">
            <a href="/classifier/">
                <i class="fa fa-angle-right fa-3x" aria-hidden="true"></i>
            </a>
        </div>
        <p>{{ form.article }}</p>
    </div>
</div>
<div class="container">

    <div class="row mb-5 pb-5">
        <div class="col-7" id="article_text">
            {% autoescape off %} {{ cls_new.ra_summary }} {% endautoescape %}
        </div>
        <div class="col-5 sticky-top" id="options">

            <form action="" method="post">
                <div id="form-div" class="row justify-content-left" data-explanations="{{ type_explanations }}">
                    {% csrf_token %}

                    {% for f, l in form.fields.types.choices %}

                    <div class="col-12 mb-0 faketype">
                        <label class="btn btn-outline-dark text-left modal_button" for="id_types_{{ f }}"
                        data-target="#explanation_modal" data-title="{{ l }}">
                            <input id="id_types_{{ f }}" name="types" class="faketype" type="checkbox" value="{{ f }}">
                            {{ l }}
                        </label>
                    </div>

                    {% endfor %}

                    <div class="w-100">
                        <label for="id_article">
                            {{ form.article }}
                        </label>
                    </div>

                    <div class="col-12 text-right pb-5 mb-5">
                        <input id="submit_form" type="submit" class="btn btn-primary" value="Готово">
                    </div>

                </div>
            </form>
        </div>
    </div>

    <div class="row footer pt-2 pr-5 pl-5 fixed-bottom justify-content-between">
        <div class="col-4">
            <p class="font-italic">Користувач: {{ cls_new.bee }}, вже класифіковано {{ done_counter }}</p>
        </div>
        <div class="col-2">
            <p class="font-weight-bold small"><a class="link" target="_blank" href="https://www.youtube.com/user/simonscat/videos">
                Кошенята за шкідливість <i class="fa fa-heart-o" aria-hidden="true"></i>  <i class="fa fa-paw" aria-hidden="true"></i>
            </a></p>
        </div>
        <div class="col-6 text-right">
            <button class="btn btn-outline-dark" id="feedback_button" data-target="#feedback_modal">Коментувати цю новину</button>
        </div>

    </div>
</div>


<div class="modal fade" id="explanation_modal" tabindex="-1" role="dialog" aria-labelledby="explanation_modal_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="explanation_modal_label"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="explanation_modal_description">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="feedback_modal" tabindex="-1" role="dialog" aria-labelledby="feedback_modal_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="feedback_modal_label">Коментар до тексту</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="feedback_modal_description">
            <form action="" method="post">
                <div id="feedback-div" class="row justify-content-center">
                    {% csrf_token %}
                    <div class="col-12">
                        <p>Напишіть коментар</p>
                        {{ feedback.comment }}
                        {{ feedback.article }}
                    </div>
                    <div class="text-center col-12">
                        <button id="submit_feedback" type="button" class="btn btn-primary" data-dismiss="modal">Надіслати</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                    </div>
                </div>
            </form>
      </div>
    </div>
  </div>
</div>

<script>
    $('#submit_feedback').click(function () {
        var form_data = $(this).closest('form').serializeArray();
        $.ajax({
            url: '{% url 'newsurls:feedback' %}',
            type : "POST",
            data: {
                'csrfmiddlewaretoken': form_data[0].value,
                'article': form_data[2].value,
                'comment': form_data[1].value
            },
            dataType: 'json'
        });
    });
</script>


{% endblock content %}

cls_tool/templates/edit_done.html
{% extends "sceleton.html" %}

{% load static from staticfiles %}

{% block content %}

<div class="container-fluid">
    <div class="row align-items-middle mt-2 mb-3">
        <div class="col-1 text-center">
            {% url 'newsurls:list_done' as done_url %}
            <a href="{{ done_url }}">
                <i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>
            </a>
        </div>
        <div class="col-10" id="heading">
            <h1><a href="{{ cls_article.article.real_url }}" target="_blank" class="link">
                #{{ cls_article.article.html_id }}</a>: {{ cls_article.article.ra_title }}</h1>
            <p class="small">класифіковано {{ cls_article.classified_at | date:'Y-m-d H:i' }}</p>
        </div>
        <div class="w-100"></div>
        <div class="jumbotron p-1 offset-1 justify-self-center">
            <p class="font-weight-bold">Режим редагування</p>
        </div>
    </div>
</div>
<div class="container">

    <div class="row mb-5">
        <div class="col-6" id="article_text">
            {% autoescape off %} {{ cls_article.article.ra_summary }} {% endautoescape %}
        </div>
        <div class="col-6" id="options">

            <form action="" method="post">
                <div id="form-div" class="row justify-content-left" data-explanations="{{ type_explanations }}">
                    {% csrf_token %}

                    {% for f, l in form.fields.types.choices %}

                    <div class="col-12 faketype">
                        <label class="btn btn-outline-dark text-left modal_button" for="id_types_{{ f }}"
                        data-target="#explanation_modal" data-title="{{ l }}">
                            <input id="id_types_{{ f }}" name="types" class="faketype" type="checkbox" value="{{ f }}">
                            {{ l }}
                        </label>
                    </div>

                    {% endfor %}

                    <div class="w-100">
                        <label for="id_article">
                            {{ form.article }}
                        </label>
                    </div>

                    <div class="col-12 text-right pb-5 mb-5">
                        <input id="submit_form" type="submit" class="btn btn-primary" value="Готово">
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row footer pt-2 pr-5 pl-5 fixed-bottom justify-content-between">
        <div class="col-3">
            <p class="font-italic">Користувач: {{ cls_new.bee }}</p>
        </div>
        <div class="col-3">
            <p class="font-weight-bold small"><a class="link" target="_blank" href="https://www.youtube.com/user/simonscat/videos">
                Кошенята за шкідливість <i class="fa fa-heart-o" aria-hidden="true"></i>  <i class="fa fa-paw" aria-hidden="true"></i>
            </a></p>
        </div>
        <div class="col-6 text-right">
            <button class="btn btn-outline-dark" id="feedback_button" data-target="#feedback_modal">Коментувати цю новину</button>
        </div>
    </div>
</div>

<form id="tagged_html_form" action="" method="post">
    {% csrf_token %}
    {{ art_html_form }}
</form>

<div class="modal fade" id="explanation_modal" tabindex="-1" role="dialog" aria-labelledby="explanation_modal_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="explanation_modal_label"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="explanation_modal_description">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="feedback_modal" tabindex="-1" role="dialog" aria-labelledby="feedback_modal_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="feedback_modal_label">Коментар до тексту</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="feedback_modal_description">
            <form action="" method="post">
                <div id="feedback-div" class="row justify-content-center">
                    {% csrf_token %}
                    <div class="col-12">
                        <p>Напишіть коментар</p>
                        {{ feedback.comment }}
                        {{ feedback.article }}
                    </div>
                    <div class="text-center col-12">
                        <button id="submit_feedback" type="button" class="btn btn-primary" data-dismiss="modal">Надіслати</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                    </div>
                </div>
            </form>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
    $(document).ready(function() {
        {% for t in form.types.value %}
        $('#id_types_' + {{ t }})
            .closest('label')
            .click();

        {% endfor %}
    });
</script>

<script>
    $('#submit_feedback').click(function () {
        var form_data = $(this).closest('form').serializeArray();
        $.ajax({
            url: '{% url 'newsurls:feedback' %}',
            type : "POST",
            data: {
                'csrfmiddlewaretoken': form_data[0].value,
                'article': form_data[2].value,
                'comment': form_data[1].value
            },
            dataType: 'json'
        });
    });
</script>



{% endblock content %}

cls_tool/templates/list_done.html
{% extends "sceleton.html" %}

{% block content %}

<div class="container">
    <div class="row justify-content-between mt-4">
        <div class="col-auto">
            <a href="/classifier/" class="link">
                <i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>
            </a>
        </div>
        <div class="col">
            <h3>Останні класифіковані тексти</h3>
        </div>
        <div class="col-12">
            <form action="{% url 'newsurls:list_done' %}" method="get" class="form-inline">
                <div class="form-row mb-2 align-items-end">
                    <div class="col-8">
                        <select class="custom-select" name="type">
                            <option value="all">Всі</option>
                            {% for t in types %}

                            {% if t.label == selected_type %}
                            <option selected value="{{ t }}">{{ t.label }}</option>
                            {% else %}
                            <option value="{{ t }}">{{ t.label }}</option>
                            {% endif %}

                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary">Показати вибрані типи</button>
                    </div>
                </div>


                <!--<select class="form-control" name="types">-->
                    <!--{% for t in types %}-->
                        <!--<option value="{{ t }}">{{ t.label }}</option>-->
                    <!--{% endfor %}-->
                <!--</select>-->
                <!--<input type="submit" class="btn btn-primary" name="types" value="Показати вибрані типи">-->
            </form>
        </div>

        <div class="w-100 mb-3"></div>

        <div class="col-12">
            <ul class="list-group">
            {% for new in done %}

                <li class="list-group-item">
                    <span class="small pr-3">{{ new.classified_at | date:'Y-m-d H:i' }} </span>
                    <a href="/classifier/edit/{{ new.article.html_id }}" class="link"> #{{ new.article.html_id }} {{ new.article.ra_title }}</a>
                    <br/>
                    {% for t in new.types.all %}
                        <span class="badge badge-secondary"> {{ t.label }} </span>
                    {% endfor %}
                </li>

            {% endfor %}
            </ul>
        </div>

        <nav class="col-12 mt-4" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if done.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">Початок</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ done.previous_page_number }}">{{ done.previous_page_number }}</a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ done.number }}</a>
                </li>
                {% if done.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ done.next_page_number }}">{{ done.next_page_number }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ done.paginator.num_pages }}">Остання {{ done.paginator.num_pages }}</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		var $pagination = $('a.page-link');
		$pagination.map(function (e) {
			var $this = $(this);
			var href = $this.attr('href');
			if ( href !== '#' ) {
				$this.attr('href', href  + '&type=' + $('form option:selected').attr('value'));
			}
		});
	})
</script>

{% endblock %}

cls_tool/templates/sceleton.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Texty Classifier</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <script src="{% static 'libs/jquery3.2.1.js' %}"></script>
    <script src="{% static 'libs/popper.js' %}"></script>
    <script src="{% static 'libs/bootstrap-4.0.0-beta.2-dist/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'libs/bootstrap-4.0.0-beta.2-dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-awesome-4.7.0/css/font-awesome.min.css'%}">

    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>

{% block content %}
{% endblock content %}

<script src="{% static 'classify_js.js' %}"></script>
</body>
</html>